import type { Metadata } from "next";
// 1. เปลี่ยนมานำเข้าฟอนต์ Kanit จาก Google Fonts
import { Kanit } from "next/font/google"; 
import Navbar from "@/components/navbar"; 
import Footer from "@/components/footer"; 
import PageTransition from "@/components/page-transition";
import "./globals.css";

// 2. ตั้งค่าน้ำหนักฟอนต์และเปิดตัวรองรับภาษาไทย (thai)
const kanit = Kanit({
  weight: ["300", "400", "500", "700", "900"],
  subsets: ["latin", "thai"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "FoodOrder App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="th" className="h-full antialiased" suppressHydrationWarning>
      <head>
        <script
          dangerouslySetInnerHTML={{
            __html: `
              try {
                var theme = localStorage.getItem('food-order-theme') === 'light' ? 'light' : 'dark';
                document.documentElement.dataset.theme = theme;
                document.documentElement.style.colorScheme = theme;
              } catch (_) {
                document.documentElement.dataset.theme = 'dark';
                document.documentElement.style.colorScheme = 'dark';
              }
            `,
          }}
        />
      </head>
      {/* 3. สั่งเรียกใช้ฟอนต์ผ่าน className โดยให้ธีมพื้นหลังคุมจาก globals.css */}
      <body className={`${kanit.className} min-h-screen w-full flex flex-col m-0 p-0`}>
        
        {/* Navbar ยืดเต็มจอซ้ายขวาด้านบน */}
        <Navbar /> 
        
        {/* เนื้อหาด้านล่างขยายตัวเพื่อดัน Footer ลงไป */}
        <main className="w-full min-w-0 flex-1 max-w-7xl mx-auto px-3 py-3 sm:px-6 sm:py-4 lg:px-8">
          <PageTransition>{children}</PageTransition>
        </main>

        {/* ส่วนท้ายของเว็บยืดเต็มจอ */}
        <Footer />

      </body>
    </html>
  );
}
