import type { Metadata } from "next";
import Script from "next/script";
import { Kanit } from "next/font/google"; 
import Navbar from "@/components/navbar"; 
import Footer from "@/components/footer"; 
import PageTransition from "@/components/page-transition";
import RealtimeRefresh from "@/components/realtime-refresh";
import CustomerOrderStatusAlerts from "@/components/customer-order-status-alerts";
import ChatMessageAlerts from "@/components/chat-message-alerts";
import "./globals.css";

const kanit = Kanit({
  weight: ["300", "400", "500", "700", "900"],
  subsets: ["latin", "thai"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "FoodOrderKmutnb",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="th" className="h-full antialiased" suppressHydrationWarning>
      <head>
        <link
          rel="stylesheet"
          href="https://cdn-uicons.flaticon.com/uicons-regular-rounded/css/uicons-regular-rounded.css"
        />
        <link
          rel="stylesheet"
          href="https://cdn-uicons.flaticon.com/uicons-brands/css/uicons-brands.css"
        />
      </head>
      <body className={`${kanit.className} min-h-screen w-full flex flex-col m-0 p-0`}>
        <Script id="food-order-theme-init" strategy="beforeInteractive">
          {`
            try {
              var theme = localStorage.getItem('food-order-theme') === 'light' ? 'light' : 'dark';
              document.documentElement.dataset.theme = theme;
              document.documentElement.style.colorScheme = theme;
            } catch (_) {
              document.documentElement.dataset.theme = 'dark';
              document.documentElement.style.colorScheme = 'dark';
            }
          `}
        </Script>
        <RealtimeRefresh />
        <CustomerOrderStatusAlerts />
        <ChatMessageAlerts />
        
        <Navbar /> 
        <main className="w-full min-w-0 flex-1 px-3 py-3 sm:px-6 sm:py-4 lg:px-8">
          <PageTransition>{children}</PageTransition>
        </main>

        <Footer />

      </body>
    </html>
  );
}
