import type { Metadata } from "next";
// 1. เปลี่ยนมานำเข้าฟอนต์ Kanit จาก Google Fonts
import { Kanit } from "next/font/google"; 
import Navbar from "@/components/navbar"; 
import Footer from "@/components/footer"; 
import "./globals.css";

// 2. ตั้งค่าน้ำหนักฟอนต์และเปิดตัวรองรับภาษาไทย (thai)
const kanit = Kanit({
  weight: ["300", "400", "500", "700", "900"],
  subsets: ["latin", "thai"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "FoodOrder App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="th" className="h-full antialiased">
      {/* 3. สั่งเรียกใช้ฟอนต์ผ่าน className และปรับ body เป็นธีมมืด bg-neutral-950 text-white */}
      <body className={`${kanit.className} min-h-screen w-full flex flex-col m-0 p-0 bg-neutral-950 text-white`}>
        
        {/* Navbar ยืดเต็มจอซ้ายขวาด้านบน */}
        <Navbar /> 
        
        {/* เนื้อหาด้านล่างขยายตัวเพื่อดัน Footer ลงไป */}
        <main className=" w-full max-w-7xl mx-auto px-6 py-4">
          {children}
        </main>

        {/* ส่วนท้ายของเว็บยืดเต็มจอ */}
        <Footer />

      </body>
    </html>
  );
}